version: "3"

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  worker:
    build: .
    command: python /code/fetch_service/tle_updater.py
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code/
