services:
  backend_dj:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"

  tle_fetcher:
    depends_on:
      - backend_dj
    build: .
    command: python /code/fetch_service/tle_updater.py
    volumes:
      - .:/code
      
  frontend:
    build:
      context: ./satfront
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/frontend
    environment:
      - API_URL=http://backend_dj:8000
    command: ng serve --host 0.0.0.0