# Generated by Django 4.2.11 on 2024-05-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Component',
            new_name='Payload',
        ),
    ]
