# Generated by Django 4.2.11 on 2024-05-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satapp', '0002_rename_component_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launcher',
            name='satellite',
        ),
        migrations.AddField(
            model_name='launcher',
            name='satellites',
            field=models.ManyToManyField(related_name='launchers', to='satapp.satellite'),
        ),
        migrations.AlterField(
            model_name='payload',
            name='satellite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='satapp.satellite'),
        ),
    ]
