# Generated by Django 4.2.11 on 2024-05-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satapp', '0003_remove_launcher_satellite_launcher_satellites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launcher',
            old_name='date',
            new_name='launch_date',
        ),
        migrations.RenameField(
            model_name='payload',
            old_name='name',
            new_name='provider',
        ),
        migrations.RemoveField(
            model_name='launcher',
            name='name',
        ),
    ]
