# Generated by Django 4.2.11 on 2024-05-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satapp', '0004_rename_date_launcher_launch_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='line1',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='line2',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='sat_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='satellite',
            name='tle_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
