# Generated by Django 4.2.10 on 2024-05-07 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('satapp', '0005_satellite_line1_satellite_line2_satellite_sat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satellites', to='satapp.owner'),
        ),
    ]
