# Generated by Django 4.2.10 on 2024-05-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satapp', '0006_alter_satellite_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='sat_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
